name: Linters

on:
  pull_request:
    paths-ignore:
      - 'notebooks/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'notebooks/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: flake8
        run: |
          flake8 --max-line-length=120
