name: Tests

on:
  pull_request:
    paths-ignore:
      - 'notebooks/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'notebooks/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
    name: Ubuntu, Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Run tests
        run: |
          python tests/test_structures.py
          python tests/test_ground_remover.py
